FROM alpine/git as clone
ARG url
WORKDIR /app
RUN git clone https://github.com/siddhi9899/ms-test.git

FROM maven:3.2-jdk-8 as build
WORKDIR /app
COPY --from=clone /app/ms-test /app
RUN mvn package

FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /app/target/SpringBootRestApiExample-1.0.0.jar /app
EXPOSE 8081
ENTRYPOINT ["sh", "-c"]
CMD ["java -jar SpringBootRestApiExample-1.0.0.jar"]