FROM java:8
FROM maven:3.5.2
RUN git clone https://github.com/siddhi9899/ms-test.git /myapp/
RUN mvn clean install
RUN cp /myapp/target/SpringBootRestApiExample-1.0.0.jar SpringBootRestApiExample-1.0.0.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "SpringBootRestApiExample-1.0.0.jar"]